version: 2
registries:
  npm-jfrog:
    type: npm-registry
    url: https://lpg.jfrog.io/artifactory/api/npm/virt-lpg-npm/
    username: ${{ secrets.JFROG_USERNAME }}
    password: ${{ secrets.JFROG_PASSWORD }}
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "15:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 10
    groups:
      production:
        dependency-type: "production"
      development:
        dependency-type: "development"
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]
    labels:
      - "npm"
      - "dependencies"
